### ISSUE TITLE
cannot install; No module named seaborne 

### ISSUE THREAD

**Issue by philipwfowler** [choderalab/automatic-equilibration-detection#9]
I cloned the repo and, after installing Miniconda, tried running reproduce.sh. This complains about seaborn

```
lambda 508 $ ./reproduce.sh 
discarding /Users/fowler/miniconda/bin from PATH
prepending /Users/fowler/tmp/automatic-equilibration-detection/examples/liquid-argon-density/conda-env/bin to PATH
characteristic timescale = 0.285 ps
timestep = 0.002846993438 ps
Minimizing positions...
Writing initial positions to initial.pdb
Traceback (most recent call last):
  File "simulate.py", line 72, in <module>
    ncfile = utils.create_netcdf_datastore(netcdf_filename, testsystem.system, initial_positions, nreplicates, niterations, observation_interval)
  File "/Users/fowler/tmp/automatic-equilibration-detection/examples/liquid-argon-density/utils.py", line 86, in create_netcdf_datastore
    raise Exception("Datafile '%s' already exists." % filename)
Exception: Datafile 'data.nc' already exists.
Traceback (most recent call last):
  File "analyze-1.py", line 19, in <module>
    import seaborn as sns
ImportError: No module named seaborn
Traceback (most recent call last):
  File "analyze-2.py", line 19, in <module>
    import seaborn as sns
ImportError: No module named seaborn
```

So I tried installing it using MacPorts (this is all on a Mac running Yosemite). 

```
port install py27-seaborn
```

And this didn't work either (although the conda env prob won't see the MacPort installed module).

**Comment by jchodera** [comment]
Thanks for catching this!  I had neglected to include `seaborn` and `matplotlib` in the conda environment provisioning line:
https://github.com/choderalab/automatic-equilibration-detection/blob/master/examples/liquid-argon-density/reproduce.sh#L14

I've checked in a fix.  Can you `git pull` to update and try again?  You may need to run `./cleanup.sh` first.

Alternatively, if you don't want to spend the time repeating the simulations, you can manually type (assuming `bash`)

```
source activate ./conda-env
conda install --yes seaborn matplotlib
python analyze-1.py
python analyze-2.py
```

Thanks again for reporting this!

**Comment by philipwfowler** [comment]
Tried a git pull and a cleanup.sh but it failed. Deleted the dir and cloned again and it works - I get all the figures. Thanks for replying so quickly, I'm presenting your paper tomorrow at our group meeting. Reproducibility like this is great and essential.     

```
lambda 507 $ ls figures/
argon-bias-variance.pdf              argon-reverse-cumulative-average.pdf
argon-density.pdf                    argon-rmse.pdf
```

**Comment by jchodera** [comment]
Awesome!  Thanks again for trying this out.
